import { Product, Order, BlogContent } from './types';

export const products: Product[] = [
    // Frutos Secos
    {
        id: '1',
        name: 'Almendras Nonpareil',
        slug: 'almendras-nonpareil',
        category: 'Frutos Secos',
        description: 'Almendras de primera calidad, ideales para snack o repostería. Ricas en proteínas y fibra.',
        priceRetail: 12000,
        priceWholesale: 9500,
        unit: 'kg',
        stock: 50,
        image: '/placeholder/almendras.jpg',
        isBestSeller: true,
    },
    {
        id: '2',
        name: 'Nueces Mariposa Extra Light',
        slug: 'nueces-mariposa',
        category: 'Frutos Secos',
        description: 'Nueces blancas, enteras y sabrosas. Fuente excelente de Omega-3.',
        priceRetail: 10500,
        priceWholesale: 8200,
        unit: 'kg',
        stock: 30,
        image: '/placeholder/nueces.jpg',
    },
    {
        id: '3',
        name: 'Avellanas Tostadas',
        slug: 'avellanas-tostadas',
        category: 'Frutos Secos',
        description: 'Avellanas europeas tostadas sin sal. Perfectas para acompañar el desayuno.',
        priceRetail: 15000,
        priceWholesale: 12000,
        unit: 'kg',
        stock: 0,
        image: '/placeholder/avellanas.jpg',
    },
    {
        id: '4',
        name: 'Castañas de Cajú W4',
        slug: 'castanas-caju',
        category: 'Frutos Secos',
        description: 'Castañas de cajú naturales, cremosas y suaves.',
        priceRetail: 14000,
        priceWholesale: 11000,
        unit: 'kg',
        stock: 45,
        image: '/placeholder/castanas.jpg',
        isNew: true,
    },
    {
        id: '11',
        name: 'Mix Tropical',
        slug: 'mix-tropical',
        category: 'Frutos Secos',
        description: 'Mezcla exótica con coco, banana, chips y frutas tropicales.',
        priceRetail: 6500,
        priceWholesale: 4800,
        unit: 'kg',
        stock: 40,
        image: '/placeholder/mix-tropical.jpg',
    },
    {
        id: '12',
        name: 'Mix Europeo',
        slug: 'mix-europeo',
        category: 'Frutos Secos',
        description: 'Selección premium de nueces, almendras, avellanas y castañas.',
        priceRetail: 12500,
        priceWholesale: 9800,
        unit: 'kg',
        stock: 30,
        image: '/placeholder/mix-europeo.jpg',
    },
    {
        id: '13',
        name: 'Mix Sin Pasas de Uva',
        slug: 'mix-sin-pasas',
        category: 'Frutos Secos',
        description: 'Combinación equilibrada de frutos secos sin el dulce de la pasa.',
        priceRetail: 8500,
        priceWholesale: 6200,
        unit: 'kg',
        stock: 50,
        image: '/placeholder/mix-sin-pasas.jpg',
    },
    {
        id: '14',
        name: 'Mix Sin Pasas y Sin Maní',
        slug: 'mix-premium-sin-pasas-mani',
        category: 'Frutos Secos',
        description: 'Solo lo mejor: almendras, nueces y castañas seleccionadas.',
        priceRetail: 11000,
        priceWholesale: 8500,
        unit: 'kg',
        stock: 25,
        image: '/placeholder/mix-premium-sin-pasas-mani.jpg',
    },
    {
        id: '15',
        name: 'Mix Salado',
        slug: 'mix-salado',
        category: 'Frutos Secos',
        description: 'Ideal para picadas, con un toque justo de sal.',
        priceRetail: 5200,
        priceWholesale: 3800,
        unit: 'kg',
        stock: 60,
        image: '/placeholder/mix-salado.jpg',
    },
    {
        id: '16',
        name: 'Mix Cervecero',
        slug: 'mix-cervecero',
        category: 'Frutos Secos',
        description: 'El acompañante perfecto para tus momentos de relax.',
        priceRetail: 4800,
        priceWholesale: 3500,
        unit: 'kg',
        stock: 100,
        image: '/placeholder/mix-cervecero.jpg',
    },
    {
        id: '17',
        name: 'Mix Semilla',
        slug: 'mix-semilla',
        category: 'Frutos Secos',
        description: 'Potencia tus ensaladas y desayunos con este mix de semillas.',
        priceRetail: 4200,
        priceWholesale: 3100,
        unit: 'kg',
        stock: 80,
        image: '/placeholder/mix-semilla.jpg',
    },
    {
        id: '18',
        name: 'Mix Cereal',
        slug: 'mix-cereal',
        category: 'Frutos Secos',
        description: 'Energía pura para tus mañanas con cereales seleccionados.',
        priceRetail: 4500,
        priceWholesale: 3200,
        unit: 'kg',
        stock: 70,
        image: '/placeholder/mix-cereal.jpg',
    },
    {
        id: '19',
        name: 'Mix con Arándanos',
        slug: 'mix-arandanos',
        category: 'Frutos Secos',
        description: 'El toque antioxidante del arándano rojo en tu mix favorito.',
        priceRetail: 9200,
        priceWholesale: 7100,
        unit: 'kg',
        stock: 35,
        image: '/placeholder/mix-arandanos.jpg',
    },
    {
        id: '20',
        name: 'Mix con Chocolate',
        slug: 'mix-chocolate',
        category: 'Frutos Secos',
        description: 'Dulzura y nutrición: frutos secos con chips de chocolate premium.',
        priceRetail: 8800,
        priceWholesale: 6500,
        unit: 'kg',
        stock: 45,
        image: '/placeholder/mix-chocolate.jpg',
    },
    {
        id: '21',
        name: 'Mix Quinoa',
        slug: 'mix-quinoa',
        category: 'Frutos Secos',
        description: 'Nutritivo y ligero con quinoa pop y frutos secos.',
        priceRetail: 5800,
        priceWholesale: 4200,
        unit: 'kg',
        stock: 50,
        image: '/placeholder/mix-quinoa.jpg',
    },

    // Especias
    {
        id: '5',
        name: 'Pimentón Ahumado Premium',
        slug: 'pimenton-ahumado',
        category: 'Especias',
        description: 'Pimentón con un intenso aroma ahumado y color vibrante.',
        priceRetail: 3500,
        priceWholesale: 2500,
        unit: '250g',
        stock: 100,
        image: '/placeholder/pimenton.jpg',
    },
    {
        id: '6',
        name: 'Cúrcuma en Polvo',
        slug: 'curcuma-polvo',
        category: 'Especias',
        description: 'Cúrcuma pura, ideal para cocinar o preparar Golden Milk.',
        priceRetail: 2800,
        priceWholesale: 1900,
        unit: '250g',
        stock: 80,
        image: '/placeholder/curcuma.jpg',
    },

    // Harinas
    {
        id: '7',
        name: 'Harina de Almendras',
        slug: 'harina-almendras',
        category: 'Harinas',
        description: 'Harina fina de almendras peladas, ideal para keto y repostería sin gluten.',
        priceRetail: 13500,
        priceWholesale: 10800,
        unit: 'kg',
        stock: 25,
        image: '/placeholder/harina-almendras.jpg',
        isBestSeller: true,
    },
    {
        id: '8',
        name: 'Harina de Coco',
        slug: 'harina-coco',
        category: 'Harinas',
        description: 'Harina orgánica de coco, rica en fibra y baja en carbohidratos.',
        priceRetail: 6000,
        priceWholesale: 4500,
        unit: 'kg',
        stock: 40,
        image: '/placeholder/harina-coco.jpg',
    },

    // Suplementos & Otros
    {
        id: '9',
        name: 'Proteína de Arveja',
        slug: 'proteina-arveja',
        category: 'Suplementos',
        description: 'Aislado de proteína de arveja 80%, ideal para veganos y deportistas.',
        priceRetail: 18000,
        priceWholesale: 14500,
        unit: 'kg',
        stock: 15,
        image: '/placeholder/proteina.jpg',
        isNew: true,
    },
    {
        id: '10',
        name: 'Mix Energético',
        slug: 'mix-energetico',
        category: 'Otros',
        description: 'Mezcla de pasas, nueces, almendras y maní. Energía rápida y saludable.',
        priceRetail: 5500,
        priceWholesale: 4000,
        unit: 'kg',
        stock: 100,
        image: '/placeholder/mix.jpg',
    }
];

export const orders: Order[] = [
    {
        id: 'ORD-001',
        customerName: 'Juan Pérez',
        date: '2026-01-20',
        items: [
            { productId: '1', productName: 'Almendras Nonpareil', quantity: 2, price: 12000 },
            { productId: '5', productName: 'Pimentón Ahumado Premium', quantity: 1, price: 3500 }
        ],
        total: 27500,
        status: 'Entregado',
        type: 'Minorista'
    },
    {
        id: 'ORD-002',
        customerName: 'Dietética "Vida Sana"',
        date: '2026-01-22',
        items: [
            { productId: '1', productName: 'Almendras Nonpareil', quantity: 10, price: 9500 },
            { productId: '7', productName: 'Harina de Almendras', quantity: 5, price: 10800 },
            { productId: '4', productName: 'Castañas de Cajú W4', quantity: 5, price: 11000 }
        ],
        total: 204000,
        status: 'Pendiente',
        type: 'Mayorista'
    },
    {
        id: 'ORD-003',
        customerName: 'Maria González',
        date: '2026-01-23',
        items: [
            { productId: '10', productName: 'Mix Energético', quantity: 1, price: 5500 }
        ],
        total: 5500,
        status: 'Pagado',
        type: 'Minorista'
    }
];

export const blogContent: BlogContent[] = [
    // Artículos
    {
        id: 'post-1',
        type: 'articulo',
        title: 'Beneficios de los Frutos Secos',
        slug: 'beneficios-frutos-secos',
        image: '/placeholder/blog-nuts.jpg',
        excerpt: 'Descubrí por qué incorporar nueces y almendras a tu dieta diaria puede mejorar tu salud cardiovascular y energía.',
        content: 'Los frutos secos son una fuente increíble de nutrientes. Aportan grasas saludables, proteínas, fibra, vitaminas y minerales. Consumir un puñado al día puede ayudar a reducir el colesterol malo y mejorar la salud del corazón. Además, son un snack perfecto para mantener la saciedad entre comidas.',
        date: '2026-01-15',
        author: 'Lic. Nutrición Clara M.'
    },
    {
        id: 'post-2',
        type: 'articulo',
        title: 'Especias que curan: Cúrcuma',
        slug: 'propiedades-curcuma',
        image: '/placeholder/blog-turmeric.jpg',
        excerpt: 'La cúrcuma no es solo color; es un potente antiinflamatorio natural. Aprendé cómo consumirla para potenciar sus efectos.',
        content: 'La cúrcuma contiene curcumina, un compuesto bioactivo con potentes propiedades medicinales. Es un antiinflamatorio natural muy efectivo y un antioxidante muy potente. Para mejorar su absorción, es ideal consumirla junto con pimienta negra.',
        date: '2026-01-10',
        author: 'Sonia'
    },
    // Recetas
    {
        id: 'receta-1',
        type: 'receta',
        title: 'Leche de Almendras Casera',
        slug: 'leche-almendras-casera',
        image: '/placeholder/recipe-milk.jpg',
        description: 'Prepará tu propia leche vegetal cremosa, sin aditivos y en pocos pasos.',
        prepTime: '15 min (+ remojo)',
        difficulty: 'Fácil',
        ingredients: [
            { productId: '1', name: 'Almendras Nonpareil', quantity: 1 }
        ],
        steps: [
            'Dejar las almendras en remojo durante al menos 8 horas.',
            'Colar y enjuagar bien las almendras.',
            'Licuar con 3 tazas de agua filtrada por cada taza de almendras.',
            'Colar con una bolsa de tela o lienzo fino apretando bien para extraer todo el líquido.',
            'Endulzar a gusto con miel, stevia o dátiles y guardar en heladera por hasta 3 días.'
        ]
    },
    {
        id: 'receta-2',
        type: 'receta',
        title: 'Budín de Banana y Nuez (Sin Harina)',
        slug: 'budin-banana-nuez',
        image: '/placeholder/recipe-cake.jpg',
        description: 'Un budín húmedo y energético, ideal para la merienda. Libre de gluten.',
        prepTime: '45 min',
        difficulty: 'Media',
        ingredients: [
            { productId: '7', name: 'Harina de Almendras', quantity: 1 },
            { productId: '2', name: 'Nueces Mariposa', quantity: 1 }
        ],
        steps: [
            'Precalentar el horno a 180°C.',
            'Pisar 3 bananas maduras hasta hacer puré.',
            'Mezclar con 3 huevos y un chorrito de esencia de vainilla.',
            'Incorporar 2 tazas de harina de almendras y 1 cucharadita de polvo de hornear.',
            'Agregar media taza de nueces picadas.',
            'Verter en una budinera aceitada o con papel manteca.',
            'Hornear por 30-40 minutos o hasta que al pinchar salga seco.'
        ]
    }
];
